# Elytradactyl by Kade
# https://plugins.akenland.com/Elytradactyl

# After editing this file, use "/elytradactyl reload" to load your changes into the server.
# To reset this config to default, delete it, and then reload.


# Use TRUE or FALSE to specify whether that mob can use Elytra to fly!
mobs:
  # For players, this will automatically activate their Elytra, instead of them having to jump while mid-air. Default FALSE.
  player: FALSE

  # NPCs from the Citizens plugin. Default TRUE.
  npc: TRUE

  # Monsters. Most will pick up dropped Elytra automatically. Default TRUE.
  monster: TRUE

  # Animals. The Elytra won't be visible, but can be equipped via commands or external editors. Default TRUE.
  animal: TRUE

  # Any other mobs. Default FALSE.
  other: FALSE

# How frequently (in ticks) to check for falling mobs. Default 20 (every second).
check-ticks: 20

# Whether to re-assign mob directions after they start gliding. Default TRUE.
# When false, most mobs only fly south. Does not affect players or NPCs.
reassign-direction: TRUE