name: Elytradactyl
version: 1.0
description: Mobs use Elytra to glide!
author: Kyle Nanakdewa
website: http://Akenland.com/plugins

main: com.kylenanakdewa.elytradactyl.ElytradactylPlugin

commands:
  elytradactyl:
    description: View plugin information, and reload the plugin.
    permission: elytradactyl.admin
    usage: /elytradactyl <version/reload>